### ISSUE TITLE
Konflikt z wtyczką Redux lub Elementor 

### ISSUE THREAD

**Issue by iNeeR123** [pay-now/paynow-woocommerce#155]
Wtyczka ma konflikt z Redux lub Elementor

Problem polega na tym, że gdy włączam edycję strony przez Elementor zatrzymuje się na ekranie ładowania.

Zauważyłem, że problem występuje tylko jeśli włączona jest wtyczka Redux i Paynow.

Jeśli wyłączę Redux lub Paynow wszystko działa prawidłowo, tzn.  jeśli wyłączę tylko "Redux" wszystko działa prawidłowo lub jeśli wyłączę tylko "Paynow" wszystko również działa poprawnie.

Próbowałem zainstalować Paynow na innej stronie gdzie jest zainstalowany Redux i natychmiast po instalacji dostaję:

`Fatal error: Uncaught Error: Call to undefined function wc_pay_by_paynow_pl_plugin_version() in /home/klient.dhosting.pl/****/****.pl/public_html/wp-content/plugins/pay-by-paynow-pl/includes/class-wc-pay-by-paynow-pl-manager.php:96 Stack trace: #0 /home/klient.dhosting.pl/****/****.pl/public_html/wp-includes/class-wp-hook.php(303): WC_Pay_By_Paynow_Pl_Manager->enqueue_admin_scripts('plugins.php') #1 /home/klient.dhosting.pl/****/****.pl/public_html/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array) #2 /home/klient.dhosting.pl/****/****.pl/public_html/wp-includes/plugin.php(470): WP_Hook->do_action(Array) #3 /home/klient.dhosting.pl/****/****.pl/public_html/wp-admin/admin-header.php(102): do_action('admin_enqueue_s...', 'plugins.php') #4 /home/klient.dhosting.pl/****/****.pl/public_html/wp-admin/plugins.php(603): require_once('/home/klient.dh...') #5 {main} thrown in /home/klient.dhosting.pl/****/****.pl/public_html/wp-content/plugins/pay-by-paynow-pl/includes/class-wc-pay-by-paynow-pl-manager.php on line 96`

**Comment by iNeeR123** [comment]
Wersja 2.4.6 #157 wydaje się, że naprawiła problem konfliktu z Elementorem. 
Dzięki
