### ISSUE TITLE
Błąd przy zapisie konfiguracji

### ISSUE THREAD

**Issue by axandar** [pay-now/paynow-woocommerce#191]
Przy próbie zapisania konfiguracji płatności pojawia się krytyczny błąd pluginu.

WordPress w wersji 6.1.1
Aktualny motyw: GutenVerse (wersja 2.2)
Aktualna wtyczka: Pay by paynow.pl (wersja 2.4.14)
Wersja PHP: 7.4.3-4ubuntu2.17

Szczegóły błędu
===================
Błąd typu E_ERROR został spowodowany w linii 260 pliku /var/www/wordpress/wp-content/plugins/pay-by-paynow-pl/vendor/php-http/curl-client/src/Client.php. Komunikat błędu: Uncaught TypeError: Return value of Http\Client\Curl\Client::getProtocolVersion() must be of the type int, string returned in /var/www/wordpress/wp-content/plugins/pay-by-paynow-pl/vendor/php-http/curl-client/src/Client.php:260
Stack trace:
#0 /var/www/wordpress/wp-content/plugins/pay-by-paynow-pl/vendor/php-http/curl-client/src/Client.php(211): Http\Client\Curl\Client->getProtocolVersion()
#1 /var/www/wordpress/wp-content/plugins/pay-by-paynow-pl/vendor/php-http/curl-client/src/Client.php(143): Http\Client\Curl\Client->prepareRequestOptions()
#2 /var/www/wordpress/wp-content/plugins/pay-by-paynow-pl/vendor/pay-now/paynow-php-sdk/src/Paynow/HttpClient/HttpClient.php(69): Http\Client\Curl\Client->sendRequest()
#3 /var/www/wordpress/wp-content/plugins/pay-by-paynow-pl/vendor/pay-now/paynow-php-sdk/src/Paynow/HttpClient/HttpClient.php(124): Paynow\HttpClient\HttpClient->send()
#4 /var/www/wordpress/wp-content/plugins/pay-by-paynow-pl/vendor/pay-now/paynow-php-sdk/src/Paynow/Service/ShopConfiguration.php(28): Pay

**Comment by axandar** [comment]
Błąd nadal występuje. W aktualnej konfiguracji nie mamy możliwości używać bramki płatności PayNow w WooCommerce w wersji 7.4.1
