### ISSUE TITLE
Kompatybilność z Elementoremq

### ISSUE THREAD

**Issue by Ghost213134** [pay-now/paynow-woocommerce#206]
Dzień dobry, po instalacji wtyczki Wordpress wyrzuca mi błędy, jestem świadomy że wtyczka miała problemy z Elementorem jednak widziałem na githubie że zostały one naprawione jednakże tjw.

`Fatal error: Uncaught Error: Call to undefined function wc_pay_by_paynow_pl_plugin_version() in /home/klient.dhosting.pl/***.pl/public_html/wp-content/plugins/pay-by-paynow-pl/includes/class-wc-pay-by-paynow-pl-manager.php:106 Stack trace: #0 /home/klient.dhosting.pl/***.pl/public_html/wp-includes/class-wp-hook.php(308): WC_Pay_By_Paynow_Pl_Manager->enqueue_admin_scripts('plugins.php') #1 /home/klient.dhosting.pl/***.pl/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array) #2 /home/klient.dhosting.pl/***.pl/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #3 /home/klient.dhosting.pl/***.pl/public_html/wp-admin/admin-header.php(118): do_action('admin_enqueue_s...', 'plugins.php') #4 /home/klient.dhosting.pl/***.pl/public_html/wp-admin/plugins.php(605): require_once('/home/klient.dh...') #5 {main} thrown in /home/klient.dhosting.pl/***.pl/public_html/wp-content/plugins/pay-by-paynow-pl/includes/class-wc-pay-by-paynow-pl-manager.php on line 106`

W związku z powyższym proszę o wsparcie, używam aktualnej wersji Wordpressa oraz Elementora, problem występuje zarówno na PHP 7.4, 8.0, 8.1

**Comment by DeadcatDev** [comment]
Ten sam błąd u mnie blokuje cały sklep.

**Comment by paynow-support** [comment]
Dzień dobry,

dziękujemy za uwagi. Próbowaliśmy odtworzyć błąd na środowisku testowym, ale bez skutku. Prosimy o przesłanie wersji WP, WC i wtyczki Paynow dla których obserwują Państwo błąd.

**Comment by pawelsk** [comment]
Dzień dobry,

Mam ten sam problem, po włączeniu wtyczki Paynow nie da się otworzyć stron w Elementorze.

WP: 6.3.2
WC: 8.2.1
Paynow: 2.4.27
Elementor: 3.16.6 

Pozdrawiam

**Comment by paynow-support** [comment]
Dzień dobry,

uprzejmie prosimy o aktualizację wtyczki. Poprawiliśmy kompatybilność z Elementorem w wersji 2.5.0.

z pozdrowieniami,
zespół paynow
