### ISSUE TITLE
Fatal w 1.0.9

### ISSUE THREAD

**Issue by rafaljosko** [pay-now/paynow-woocommerce#32]
[21-May-2020 17:04:04 UTC] PHP Warning:  include_once(/private_html/wp-content/plugins/paynow-woocommerce-1.0.9/vendor/autoload.php): failed to open stream: No such file or directory in /private_html/wp-content/plugins/paynow-woocommerce-1.0.9/woocommerce-gateway-paynow.php on line 31
[21-May-2020 17:04:04 UTC] PHP Warning:  include_once(): Failed opening '/private_html/wp-content/plugins/paynow-woocommerce-1.0.9/vendor/autoload.php' for inclusion (include_path='.:/opt/alt/php72/usr/share/pear') in /private_html/wp-content/plugins/paynow-woocommerce-1.0.9/woocommerce-gateway-paynow.php on line 31
[21-May-2020 17:04:04 UTC] PHP Fatal error:  Uncaught Error: Class 'Paynow\Client' not found in /private_html/wp-content/plugins/paynow-woocommerce-1.0.9/includes/class-wc-gateway-paynow.php:95
Stack trace:
/private_html/wp-content/plugins/paynow-woocommerce-1.0.9/includes/class-wc-gateway-paynow.php(63): WC_Gateway_Paynow->init_paynow_client()
#1 /private_html/wp-content/plugins/paynow-woocommerce-1.0.9/includes/class-wc-paynow-notification-handler.php(12): WC_Gateway_Paynow->__construct()
#2 /private_html/wp-content/plugins/paynow-woocommerce-1.0.9/includes/class-wc-paynow-notification-handler.php(141): WC_Gateway_Paynow_Notification_Handler->__construct()
#3 /private_html/wp-content/plugins/paynow-woocommerce-1.0.9/woocommerce-gateway-paynow.php(35): include_once('/home...')
#4 /private_htm in /private_html/wp-content/plugins/paynow-woocommerce-1.0.9/includes/class-wc-gateway-paynow.php on line 95

**Comment by emilleszczak2** [comment]
Czy pobrałeś plik paynow.zip?

**Comment by rafaljosko** [comment]
Pobralem wersje otagowana 1.0.9

czw., 21 maj 2020, 19:14 użytkownik Emil Leszczak <notifications@github.com>
napisał:

**Comment by emilleszczak2** [comment]
Po logach wnioskuję że pobrałeś plik ze kodem źródłowym a nie gotowy moduł. Należy pobrać za pośrednictwem pliku paynow.zip: https://github.com/pay-now/paynow-woocommerce/releases/download/v1.0.9/paynow.zip

**Comment by rafaljosko** [comment]
Dobra wróciłem do domu :) - masz rację - na telefonie pobrałem 1.0.9 wersję developerską :)
